export const toolbarOptions = [
  [{ header: [1, 2, 3, 4, 5, 6, false] }, { font: [] }],
  ["bold", "italic", "underline", "strike"],
  [{ color: [] }, { background: [] }],
  [{ align: [] }],
  [{ list: "bullet" }, { list: "ordered" }],
  [{ indent: "-1" }, { indent: "+1" }],
  ["link", "image", "video"],
  ["blockquote", "code-block"],
  ["clean"],
];

export const formats = [
  "link",
  "bold",
  "font",
  "list",
  "image",
  "video",
  "align",
  "color",
  "clean",
  "header",
  "italic",
  "bullet",
  "indent",
  "tiktok",
  "strike",
  "twitter",
  "facebook",
  "underline",
  "instagram",
  "code-block",
  "word-count",
  "background",
  "blockquote",
];
